#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidApp4.Resource", IsApplication=true)]

namespace AndroidApp4
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Robotics.Mobile.Core.Resource.String.library_name = global::AndroidApp4.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int planets_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonSignInStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSignUpStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit_text_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int heart_graph_1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int hrgraph = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int mail = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ProgressBarStyle = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08001c
			public const int ButtonSearchBle = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int TextBoxResults = 2131230749;
			
			// aapt resource value: 0x7f080006
			public const int blue = 2131230726;
			
			// aapt resource value: 0x7f080003
			public const int btnDialogEmail = 2131230723;
			
			// aapt resource value: 0x7f080019
			public const int btnSignIn = 2131230745;
			
			// aapt resource value: 0x7f08001b
			public const int btnSignUp = 2131230747;
			
			// aapt resource value: 0x7f080014
			public const int button1 = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int button2 = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int button3 = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int button4 = 2131230743;
			
			// aapt resource value: 0x7f080008
			public const int edit = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int edit2 = 2131230729;
			
			// aapt resource value: 0x7f08000e
			public const int gbutton = 2131230734;
			
			// aapt resource value: 0x7f080005
			public const int historybutton = 2131230725;
			
			// aapt resource value: 0x7f08000c
			public const int homebutton = 2131230732;
			
			// aapt resource value: 0x7f08000f
			public const int imageView1 = 2131230735;
			
			// aapt resource value: 0x7f080013
			public const int linearLayout1 = 2131230739;
			
			// aapt resource value: 0x7f08000b
			public const int progressBar1 = 2131230731;
			
			// aapt resource value: 0x7f08001e
			public const int relativeLayout1 = 2131230750;
			
			// aapt resource value: 0x7f080004
			public const int relativeLayout2 = 2131230724;
			
			// aapt resource value: 0x7f08001f
			public const int spinning = 2131230751;
			
			// aapt resource value: 0x7f08000a
			public const int submit = 2131230730;
			
			// aapt resource value: 0x7f080010
			public const int textView1 = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int textView2 = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int textView3 = 2131230738;
			
			// aapt resource value: 0x7f080018
			public const int txtCreateAccount = 2131230744;
			
			// aapt resource value: 0x7f080001
			public const int txtEmail = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int txtFirstName = 2131230720;
			
			// aapt resource value: 0x7f08001a
			public const int txtOr = 2131230746;
			
			// aapt resource value: 0x7f080002
			public const int txtPassword = 2131230722;
			
			// aapt resource value: 0x7f08000d
			public const int wblue = 2131230733;
			
			// aapt resource value: 0x7f080007
			public const int wbutton = 2131230727;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_sign_up = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Goals = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int History = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Landing = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Workout = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int ApplicationName = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int planet_prompt = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int dialog_animation = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
